### ISSUE TITLE
Interesting essay/book-review on UBI concept

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/UBI-examples#15]
Benjamin Friedman, the William Joseph Maier Professor of Political Economy at Harvard University, has published a sympathetic review of a Harvard University Press book entitled *Basic Income* in the October 12, 2017, issue of the *New York Review of Books*.  Like most reviews in the NYRB, it is more like a wide-ranging essay that brings in the book under review at some point in the essay.  Friedman is sympathetic, but points out what he sees as practical implementation problems that are closely related to the counterfactual simulations we want Tax-Calculator to do eventually.

Given that many of you have spent quite a bit of time working on UBI-related matters, I thought you would enjoy reading an essay that discusses UBI at a higher level than your detailed data and simulation work.  It's always good to have context for the detailed work we do every day.

Here is a [link to the essay/review](http://www.nybooks.com/articles/2017/10/12/basic-income-born-to-be-free/?sub_key=59d4e4b2eab50).  It is available only to subscribers, but I can share it with others.
Let me know if the link doesn't work and I'll do something else to make the essay/review available to all of you.

**Comment by martinholmer** [comment]
Forgot to address issue #15 to each of you.

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

**Comment by Amy-Xu** [comment]
Martin@martinholmer, thank you for sharing the article. It's a very interesting read.
